### ISSUE TITLE
Default spec.postgresql_image subject to dockerhub pull limits

### ISSUE THREAD

**Issue by ChetHosey** [windup/windup-operator#70]
The default value of spec.postgresql_image is 'centos/postgresql-96-centos7:latest', which is subject to Docker Hub pull limits. A better choice might be 'registry.redhat.io/rhel8/postgresql-96:latest'.

**Comment by carlosthe19916** [comment]
The postgresql container image is now `registry.access.redhat.com/rhscl/postgresql-10-rhel7:1` which has public access. I believe this solves this issue.
